# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Set environment variables
      run: echo "PORT=7540" >> $GITHUB_ENV
    
    - name: Start the server
      run: go run ./cmd/*.go & echo $! > server.pid
    
    - name: Wait for the server to start
      run: sleep 5
    
    - name: Run tests
      run: go test -v ./...

    - name: Stop the server
      if: always()
      run: kill $(cat server.pid)
